{
   "formtabs":[
   {
      "MIGX_id":2,
      "caption":"Инфо",
      "print_before_tabs":"0",
      "fields":[
      {
         "MIGX_id":6,
         "field":"name",
         "caption":"Название",
         "pos":1
      },
      {
         "MIGX_id":7,
         "field":"value",
         "caption":"Значение",
         "description":"",
         "description_is_code":"0",
         "inputTV":"",
         "inputTVtype":"",
         "validation":"",
         "configs":"",
         "restrictive_condition":"",
         "display":"",
         "sourceFrom":"config",
         "sources":"",
         "inputOptionValues":"",
         "default":"",
         "useDefaultIfEmpty":"0",
         "pos":2
      },
      {
         "MIGX_id":8,
         "field":"active",
         "caption":"Активный",
         "description":"",
         "description_is_code":"0",
         "inputTV":"",
         "inputTVtype":"listbox",
         "configs":"",
         "sourceFrom":"config",
         "sources":"[]",
         "inputOptionValues":"Активный==1||Скрытый==0",
         "default":1,
         "pos":3
      }
      ],
      "pos":1
   }
   ],
   "contextmenus":"",
   "actionbuttons":"",
   "columnbuttons":"",
   "filters":"",
   "extended":{
      "migx_add":"",
      "disable_add_item":"",
      "add_items_directly":"",
      "formcaption":"",
      "update_win_title":"",
      "win_id":"",
      "maxRecords":"",
      "addNewItemAt":"bottom",
      "multiple_formtabs":"",
      "multiple_formtabs_label":"",
      "multiple_formtabs_field":"",
      "multiple_formtabs_optionstext":"",
      "multiple_formtabs_optionsvalue":"",
      "actionbuttonsperrow":1,
      "winbuttonslist":"",
      "extrahandlers":"this.handleColumnSwitch",
      "filtersperrow":1,
      "packageName":"",
      "classname":"",
      "task":"",
      "getlistsort":"",
      "getlistsortdir":"",
      "sortconfig":"",
      "gridpagesize":"",
      "use_custom_prefix":"0",
      "prefix":"",
      "grid":"",
      "gridload_mode":1,
      "check_resid":1,
      "check_resid_TV":"",
      "join_alias":"",
      "has_jointable":"yes",
      "getlistwhere":"",
      "joins":"",
      "cmpmaincaption":"",
      "cmptabcaption":"",
      "cmptabdescription":"",
      "cmptabcontroller":"",
      "winbuttons":"",
      "onsubmitsuccess":"",
      "submitparams":""
   },
   "columns":[
   {
      "MIGX_id":1,
      "header":"id",
      "dataIndex":"MIGX_id",
      "show_in_grid":"no"
   },
   {
      "MIGX_id":2,
      "header":"Название",
      "dataIndex":"name",
      "width":120,
      "sortable":1,
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderchunktpl":"",
      "renderoptions":"",
      "editor":"this.textEditor"
   },
   {
      "MIGX_id":5,
      "header":"Значение",
      "dataIndex":"value",
      "width":120,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderchunktpl":"",
      "renderoptions":"",
      "editor":"this.textEditor"
   },
   {
      "MIGX_id":2,
      "header":"Активный",
      "dataIndex":"active",
      "width":50,
      "sortable":1,
      "show_in_grid":1,
      "renderer":"this.renderSwitchStatusOptions",
      "clickaction":"switchOption",
      "selectorconfig":"",
      "renderchunktpl":"",
      "renderoptions":[
      {
         "MIGX_id":1,
         "name":"Активный",
         "value":1,
         "clickaction":"",
         "handler":"",
         "image":"assets/img/tick.png"
      },
      {
         "MIGX_id":2,
         "name":"Скрытый",
         "value":"0",
         "clickaction":"",
         "handler":"",
         "image":"assets/img/empty-tick.png"
      }
      ],
      "editor":""
   }
   ]
}
